name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --all-features --verbose
    - name: Check format
      run: cargo fmt --check --verbose
    - name: Check lints
      run: cargo clippy --all-features --verbose -- --deny clippy::all
    - name: Run tests
      run: cargo test --features fastnear-data-server --verbose
